#ifndef __CONFIG_H_
#define __CONFIG_H_

#define NET_PORT 8888
#define BACK_LOG 10
#define NET_BUFSIZE (16*1024)
#define UNIT_BUFSIZE 16

#define SETTINGS_MAXCOUNT 16
#define SETTINGS_BUFSIZE (SETTINGS_MAXCOUNT*UNIT_BUFSIZE)

#define ENCODES_MAXCOUNT 512
#define ENCODES_BUFSIZE (ENCODES_MAXCOUNT*UNIT_BUFSIZE)

#define STATUS_BUFSIZE 32

#endif // __CONFIG_H_